name: Build Flutter App (Linux ARM64 Only)

on: workflow_dispatch

jobs:
  build_linux_arm64:
    name: Build Linux ARM64
    # استفاده از رانر بومی ARM برای بالاترین سرعت و حذف شبیه‌ساز
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake libgtk-3-dev pkg-config
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'
          
      - name: Get Packages
        run: flutter pub get
        
      - name: Build Linux ARM64
        run: flutter build linux --release
        
      - name: Zip Linux Build
        run: |
          cd build/linux/arm64/release/bundle
          zip -r ../../../../../rdnbenet-linux-arm64.zip *
          
      - name: Upload Linux ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-zip
          path: rdnbenet-linux-arm64.zip

  upload-release:
    permissions: write-all
    needs: [build_linux_arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Download Linux ARM64 ZIP
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64-zip
          path: ./out/linux-arm64

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/linux-arm64/*
          tag_name: ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
